# 안녕, 텐서플로

먼저 (당연히) 텐스플로 라이브러리 임포트

In [1]:
import tensorflow as tf

상수 선언

In [2]:
hello = tf.constant('Hello TensorFlow!')

`Tensor` 라는 자료형에 상수를 담고 있음을 의미

In [3]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

랭크(Rank)와 셰이프(Shape)
- 랭크는 차원의 수
- 셰이프는 각 차원의 요소 개수 (텐서의 구조)

In [4]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)

In [5]:
a

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [6]:
b

<tf.Tensor 'Const_2:0' shape=() dtype=int32>

In [7]:
c

<tf.Tensor 'Add:0' shape=() dtype=int32>

- **그래프** 는 텐서들의 연산 모음
- 그래프 실행은 `Session` 안에서 이뤄져야 한다

In [8]:
sess = tf.Session()

In [9]:
sess

In [10]:
sess.run(hello)

b'Hello TensorFlow!'

In [11]:
sess.run(c)

42

In [12]:
sess.close()

플레이스홀더(Placeholer)와 변수(Variable)
- **플레이스홀더**는 그래프에 사용할 입력값을 나중에 받기 위해 사용하는 매개 변수(parameter)
- **변수**는 그래프를 최적화하는 용도로 텐서플로가(학습 함수들이) 학습한 결과를 갱신하기 위해 사용하는 변수

In [13]:
X = tf.placeholder(tf.float32, [None, 3])

In [14]:
X

<tf.Tensor 'Placeholder:0' shape=(?, 3) dtype=float32>

나중에 플레이스홀더 `X`에 넣을 자료를 정의하려면...

In [15]:
x_data = [[1, 2, 3], [4, 5, 6]]

변수를 정의 해보자

`W` 는 [3, 2] 행렬 형태의 텐서, `b`는 [2, 1] 행렬 형태의 텐서  
`random_normal` 함수를 이용해서 <u>정규분포(normal distribution)</u>의 무작위 값으로 초기화

In [18]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

In [20]:
W

<tf.Variable 'Variable_2:0' shape=(3, 2) dtype=float32_ref>

In [21]:
b

<tf.Variable 'Variable_3:0' shape=(2, 1) dtype=float32_ref>

> 행렬곱?
> - 행렬곱 A\*B에 대하여, 행렬 A의 열 수와 행렬 B의 행 수는 같아야 한다.
> - 행렬곱 A\*B를 계산한 행렬 AB의 크기는 A의 행 개수와 B의 열 개수가 된다.

In [22]:
expr = tf.matmul(X, W) + b

In [23]:
sess = tf.Session()

`global_variables_initializer` 함수는 앞에서 정의한 변수들을 초기화 하는 함수

In [24]:
sess.run(tf.global_variables_initializer())

In [25]:
x_data

[[1, 2, 3], [4, 5, 6]]

In [31]:
sess.run(W)

array([[ 0.7727929 , -2.4401197 ],
       [-1.1760299 , -0.16698602],
       [-0.42401314,  0.8820491 ]], dtype=float32)

In [30]:
sess.run(b)

array([[-0.09652274],
       [-0.16459255]], dtype=float32)

`feed_dict` 매개변수는 그래프를 실행할 때 사용할 입력값을 지정

In [32]:
sess.run(expr, feed_dict={X: x_data})

array([[-2.9478292 , -0.22446722],
       [-5.49765   , -5.4677076 ]], dtype=float32)

In [33]:
sess.close()